alter session set nls_date_format='DD-MON-YYYY'; 

CREATE TYPE PHONE_NUMBER AS TABLE OF NUMBER(11);

CREATE TABLE HANDGUN(
	HANDGUNID NUMBER(4) NOT NULL PRIMARY KEY,
	CALIBER VARCHAR2(15) NOT NULL,
	OVERALLLENGTH NUMBER(2, 2) NOT NULL,
	PRODUCTIONYEAR DATE NOT NULL,
	BARRELLENGTH NUMBER(2, 2) NOT NULL,
	HTRIGGER VARCHAR2(50) NOT NULL,
	HEIGHT NUMBER(2, 2),
	WIDTH NUMBER(2, 2),
	WEIGHT NUMBER(2, 2),
	TOTALCAPACITY NUMBER(2) NOT NULL,
	FRAME VARCHAR2(50) NOT NULL,
	LOANPRICE NUMBER(4, 2),
	CATNAME VARCHAR2(20) NOT NULL,
	MANUFACTURERID NUMBER(2) NOT NULL,
	CONSTRAINT handgun_category_fk
		FOREIGN KEY(CATNAME)
		REFERENCES CATEGORY(CATNAME)
		ON DELETE CASCADE,
	CONSTRAINT handgun_manufacturer_fk
		FOREIGN KEY(MANUFACTURERID)
		REFERENCES MANUFACTURER(MANUFACTURERID)
		ON DELETE CASCADE);
		
CREATE TABLE CATEGORY(
	CATNAME VARCHAR2(20) NOT NULL PRIMARY KEY);

CREATE TABLE MANUFACTURER(
	MANUFACTURERID NUMBER(2) NOT NULL PRIMARY KEY,
	NAME VARCHAR2(50) NOT NULL,
	COUNTRYNAME VARCHAR2(15) NOT NULL,
	PHONENUMBER PHONE_NUMBER,
	WEBADDRESS VARCHAR2(30))
	NESTED TABLE PHONENUMBER STORE AS PHONE_NUMBER_S;
	
--Derived attribute eklenecek view kullanarak.
CREATE TABLE CUSTOMER(
	CUSTOMERID NUMBER(4) NOT NULL PRIMARY KEY,
	NAME VARCHAR2(50) NOT NULL,
	ADDRESS VARCHAR2(100) NOT NULL,	
	BIRTHDAY DATE NOT NULL,
	--AGE NUMBER(2),
	PHONENUMBER PHONE_NUMBER)
	NESTED TABLE PHONENUMBER STORE AS PHONE_NUMBER_C;

CREATE TABLE ROOM(
	ROOMID NUMBER(2) NOT NULL PRIMARY KEY,
	TARGETNUMBER NUMBER(2),
	EMPLOYEEID NUMBER(2) NOT NULL,
	CONSTRAINT room_roomofficer_fk
		FOREIGN KEY (EMPLOYEEID)
		REFERENCES ROOMOFFICER (EMPLOYEEID)
		ON DELETE CASCADE);

--Derived attribute eklenecek view kullanarak (AGE).
CREATE TABLE EMPLOYEE(
	EMPLOYEEID NUMBER(2) NOT NULL PRIMARY KEY,
	NAME VARCHAR2(50) NOT NULL,
	DEPARTMENT VARCHAR2(11) NOT NULL,
	--AGE NUMBER(2),
	BIRTHDAY DATE NOT NULL,
	SALARY NUMBER(5, 2) NOT NULL,
	PHONENUMBER PHONE_NUMBER,
	ADDRESS VARCHAR2(100) NOT NULL)
	NESTED TABLE PHONENUMBER STORE AS PHONE_NUMBER_E;

CREATE TABLE WORKER(	
	EMPLOYEEID NUMBER(2) NOT NULL PRIMARY KEY,
	ROLE VARCHAR2(15),
	CONSTRAINT worker_employee_fk
		FOREIGN KEY (EMPLOYEEID)
		REFERENCES EMPLOYEE(EMPLOYEEID)
		ON DELETE CASCADE);

CREATE TABLE ROOMOFFICER(
	EMPLOYEEID NUMBER(2) NOT NULL PRIMARY KEY,
	CONSTRAINT roomofficer_employee_fk
		FOREIGN KEY (EMPLOYEEID)
		REFERENCES EMPLOYEE (EMPLOYEEID)
		ON DELETE CASCADE);
  
CREATE TABLE BORROWER(
	CUSTOMERID NUMBER(4) NOT NULL PRIMARY KEY,
	ROOMID NUMBER(2) NOT NULL,
	HANDGUNID NUMBER(4) NOT NULL,
	CONSTRAINT borrower_customer_fk
		FOREIGN KEY (CUSTOMERID)
		REFERENCES CUSTOMER (CUSTOMERID)
		ON DELETE CASCADE,
	CONSTRAINT borrower_room_fk
		FOREIGN KEY (ROOMID)
		REFERENCES ROOM (ROOMID)
		ON DELETE CASCADE,
	CONSTRAINT borrower_handgun_fk
		FOREIGN KEY (HANDGUNID)
		REFERENCES HANDGUN (HANDGUNID)
		ON DELETE CASCADE);